apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raja-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/raja198383/git-ops.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
